### ISSUE TITLE
Ollama Package: Not handling context timeout issues on streaming response.

### ISSUE THREAD

**Issue by ardan-bkennedy** [tmc/langchaingo#948]
When a context timeout occurs at the time a response is being provided, this line of code throws a panics. It appears `resp.Message` is  `nil` and it's not being checked.

https://github.com/tmc/langchaingo/blob/main/llms/ollama/ollamallm.go#L152

```
goroutine 1 [running]:
github.com/tmc/langchaingo/llms/ollama.(*LLM).GenerateContent(0x14000444140, {0x104a823f0, 0x14000092000}, {0x140003044e0, 0x1, 0x104dc0f18?}, {0x14000320050, 0x1, 0x14000320050?})
	/Users/bill/code/go/src/github.com/ardanlabs/ai-training/vendor/github.com/tmc/langchaingo/llms/ollama/ollamallm.go:159 +0x7ec
github.com/tmc/langchaingo/llms.GenerateFromSinglePrompt({0x104a823f0, 0x14000092000}, {0x104a80b80, 0x14000444140}, {0x14000493980, 0x1974}, {0x14000320050, 0x1, 0x1})
	/Users/bill/code/go/src/github.com/ardanlabs/ai-training/vendor/github.com/tmc/langchaingo/llms/llms.go:41 +0x148
github.com/tmc/langchaingo/llms/ollama.(*LLM).Call(...)
	/Users/bill/code/go/src/github.com/ardanlabs/ai-training/vendor/github.com/tmc/langchaingo/llms/ollama/ollamallm.go:44
main.questionResponse({0x104a823f0, 0x14000092000}, {0x14000136168, 0x17}, {0x14000432000, 0x5, 0x14000114600?})
```

**Comment by nickisworking** [comment]
i had the similar issue,  #961 may solve this

**Comment by ardan-bkennedy** [comment]
It's not that I couldn't solve the problem with a larger timeout. This is something that needs to be fixed in the code so when a timeout occurs it happens gracefully.

**Comment by ardan-bkennedy** [comment]
Nice, you provided a PR to fix it. very cool.  Thanks.  At this point I have a properly set timeout.
